# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
dist: xenial   # required for Python >= 3.7
sudo: yes
python:
  - "3.5"
  - "3.6"
  - "3.7"
  
# command to install dependencies
install:
  - pip install -r docs/requirements.txt

# command to run tests
before_script:
  - pip install .

script:
  - pytest --cov=./preparenovonix

# Code coverage
after_success:
  - codecov